export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_BY_GENRE = 'FETCH_BY_GENRE';
export const FETCH_BY_GENRE_SUCCESS = 'FETCH_BY_GENRE_SUCCESS';
export const FETCH_BY_GENRE_FAILURE = 'FETCH_BY_GENRE_FAILURE';

export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

export const FETCH_TRENDING = 'FETCH_TRENDING';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';

export const FETCH_DETAIL = 'FETCH_DETAIL';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAILURE = 'FETCH_DETAIL_FAILURE';

export const FETCH_CAST = 'FETCH_CAST';
export const FETCH_CAST_SUCCESS = 'FETCH_CAST_SUCCESS';
export const FETCH_CAST_FAILURE = 'FETCH_CAST_FAILURE';

export const FETCH_TRAILERS = 'FETCH_TRAILERS';
export const FETCH_TRAILERS_SUCCESS = 'FETCH_TRAILERS_SUCCESS';
export const FETCH_TRAILERS_FAILURE = 'FETCH_TRAILERS_FAILURE';
