export const API_KEY = '?api_key=2401a0e43ad659da80761c5b927e5930';
export const API_KEY_ALT = '&api_key=2401a0e43ad659da80761c5b927e5930';
export const URL_LIST = 'https://api.themoviedb.org/3/discover/movie';
export const URL_TRENDING = 'https://api.themoviedb.org/3/trending/all/day';
export const URL_POPULAR_MOVIE = 'https://api.themoviedb.org/3/movie/popular';
export const URL_LATEST_MOVIE = 'https://api.themoviedb.org/3/movie/latest';
export const URL_TOP_RATED_MOVIE =
	'https://api.themoviedb.org/3/movie/top_rated';
export const URL_MOVIE_CATEGORIES =
	'https://api.themoviedb.org/3/genre/movie/list';
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/';
export const URL_PERSON = 'https://api.themoviedb.org/3/person/';
export const URL_IMG = 'https://image.tmdb.org/t/p/';
export const URL_YOUTUBE = 'https://www.youtube.com/embed/';
export const URL_CAST = '/casts';
export const URL_VIDEO = '/videos';
export const IMG_BACKDROP_SMALL = 'w300';
export const IMG_BACKDROP_MEDIUM = 'w780';
export const IMG_BACKDROP_LARGE = 'w1280';
export const IMG_BACKDROP_ORIGINAL = 'original';
export const IMG_POSTER_SMALL = 'w342';
export const IMG_POSTER_MEDIUM = 'w500';
export const IMG_POSTER_LARGE = 'w780';
export const IMG_POSTER_ORIGINAL = 'original';
export const CAST_MAX_NUM = 5;
export const TRAILER_MAX_NUM = 3;
export const LANGUAGE_SPA = '&language=es-ES';
export const LANGUAGE_ENG = '&language=en-US';
export const DISCOVER_MOVIES_BY_CATEGORY = '&whit_genres=';
