export const FETCH_LATEST_MOVIES = 'FETCH_LATEST_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_POPULAR_SERIES = 'FETCH_POPULAR_SERIES';
export const FETCH_LATEST_SERIES = 'FETCH_LATEST_SERIES';
export const FETCH_CASTS = 'FETCH_CASTS';
export const FETCH_TRAILERS = 'FETCH_TRAILERS';
export const SEARCH = 'SEARCH';
